# Generated by Django 3.1.1 on 2020-11-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0003_auto_20201102_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
