# Generated by Django 3.1.1 on 2020-11-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0004_auto_20201102_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='subject',
            new_name='name',
        ),
    ]
