# Generated by Django 3.1.1 on 2020-11-03 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0005_auto_20201102_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='name',
            new_name='subject',
        ),
    ]
