# Generated by Django 3.1.1 on 2020-11-03 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0007_auto_20201103_0010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Template',
        ),
    ]
