# Generated by Django 3.1.1 on 2020-11-12 01:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0009_profile_templatelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
