# Generated by Django 3.1.1 on 2020-11-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0010_auto_20201111_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_text',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
