# Generated by Django 3.1.1 on 2020-11-12 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0012_auto_20201111_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc.tag', to_field='tag_name'),
        ),
    ]
